# Generated by Django 5.1.2 on 2025-03-20 13:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id_maps', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldMaps',
            fields=[
                ('id_field_maps', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.maps')),
            ],
        ),
        migrations.CreateModel(
            name='DataMaps',
            fields=[
                ('id_data_maps', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_field_maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.maps')),
            ],
        ),
    ]
