# Generated by Django 5.1.2 on 2025-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_maps_fieldmaps_datamaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='photo_maps',
            field=models.ImageField(blank=True, null=True, upload_to='maps_photo/'),
        ),
    ]
