# Generated by Django 5.1.2 on 2025-03-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_maps_photo_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamaps',
            name='id_field_maps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.fieldmaps'),
        ),
    ]
