# Generated by Django 5.1.2 on 2025-06-16 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_datamaps_id_field_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dataset', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('kategori', models.CharField(max_length=100)),
                ('properties', models.JSONField()),
            ],
        ),
    ]
