# Generated by Django 5.1.2 on 2025-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_geodataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
