# Generated by Django 5.1.2 on 2025-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_uploadprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataset',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
