# Generated by Django 5.1.2 on 2025-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_geodataset_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
