# Generated by Django 5.1.2 on 2025-07-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_geodataset_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodataset',
            name='pending',
        ),
    ]
