# Generated by Django 5.1.2 on 2025-07-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_geodataset_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamaps',
            name='id_field_maps',
        ),
        migrations.RemoveField(
            model_name='fieldmaps',
            name='id_maps',
        ),
        migrations.DeleteModel(
            name='GarisPantai',
        ),
        migrations.DeleteModel(
            name='JalanLingkungan',
        ),
        migrations.DeleteModel(
            name='KawasanKumuh',
        ),
        migrations.DeleteModel(
            name='DataMaps',
        ),
        migrations.DeleteModel(
            name='FieldMaps',
        ),
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
