# Generated by Django 5.1.2 on 2025-03-18 19:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id_kecamatan', models.AutoField(primary_key=True, serialize=False)),
                ('kecamatan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('kelurahan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perumahan',
            fields=[
                ('id_perumahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_perumahan', models.CharField(max_length=255)),
                ('lokasi_perumahan', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rumah',
            fields=[
                ('id_rumah', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=255)),
                ('lokasi_rumah', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kelurahan')),
                ('nama_perumahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.perumahan')),
            ],
        ),
    ]
