# Generated by Django 5.1.2 on 2025-03-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='rawan_bencana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rumah',
            name='status_rumah',
            field=models.CharField(blank=True, choices=[('RUMAH_LAYAK_HUNI', 'Rumah Layak Huni'), ('RUMAH_TIDAK_LAYAK_HUNI', 'Rumah Tidak Layak Huni')], max_length=30, null=True),
        ),
    ]
