# Generated by Django 5.1.2 on 2025-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0002_rumah_rawan_bencana_rumah_status_rumah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='status_rumah',
            field=models.CharField(choices=[('RUMAH_LAYAK_HUNI', 'Rumah Layak Huni'), ('RUMAH_TIDAK_LAYAK_HUNI', 'Rumah Tidak Layak Huni')], max_length=30),
        ),
    ]
