# Generated by Django 5.1.2 on 2025-04-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0003_alter_rumah_status_rumah'),
    ]

    operations = [
        migrations.AddField(
            model_name='perumahan',
            name='alamat_lengkap_perumahan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan'),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.kelurahan'),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='perumahan_subsidi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perumahan',
            name='photo_perumahan',
            field=models.ImageField(blank=True, null=True, upload_to='perumahan_photo/'),
        ),
    ]
