# Generated by Django 5.1.2 on 2025-04-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0004_perumahan_alamat_lengkap_perumahan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perumahan',
            name='kecamatan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan'),
        ),
    ]
