# Generated by Django 5.1.2 on 2025-04-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0008_alter_perumahan_alamat_lengkap_perumahan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='rumah',
            name='kelurahan',
        ),
    ]
