# Generated by Django 5.1.2 on 2025-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0009_remove_rumah_kecamatan_remove_rumah_kelurahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='photo_rumah',
            field=models.ImageField(blank=True, null=True, upload_to='rumah_photo/'),
        ),
    ]
