# Generated by Django 5.1.2 on 2025-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0011_rumah_alamat_rumah_rumah_jumlah_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
