# Generated by Django 5.1.2 on 2025-04-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0012_alter_rumah_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='block',
        ),
    ]
