# Generated by Django 5.1.2 on 2025-04-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0013_remove_rumah_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='rawan_bencana',
        ),
    ]
