# Generated by Django 5.1.2 on 2025-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0014_remove_rumah_rawan_bencana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='alamat_rumah',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='jumlah_kk',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='nama_pemilik',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='status_luas',
            field=models.CharField(choices=[('LUAS_RUMAH_CUKUP', 'Luas Rumah Cukup'), ('LUAS_RUMAH_KURANG', 'Luas Rumah Kurang')], default=1, max_length=30),
        ),
    ]
