# Generated by Django 5.1.2 on 2025-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0015_alter_rumah_alamat_rumah_alter_rumah_jumlah_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='nama_pemilik',
            field=models.CharField(max_length=255),
        ),
    ]
