# Generated by Django 5.1.2 on 2025-04-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0016_alter_rumah_nama_pemilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='alamat_rumah',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='jumlah_kk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='status_luas',
            field=models.CharField(choices=[('LUAS_RUMAH_CUKUP', 'Luas Rumah Cukup'), ('LUAS_RUMAH_KURANG', 'Luas Rumah Kurang')], max_length=30),
        ),
    ]
