# Generated by Django 5.1.2 on 2025-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0017_alter_rumah_alamat_rumah_alter_rumah_jumlah_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='rumah_sewa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
