# Generated by Django 5.1.2 on 2025-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0018_rumah_rumah_sewa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='rumah_sewa',
            field=models.BooleanField(default=False),
        ),
    ]
