# Generated by Django 5.1.2 on 2025-04-24 03:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0019_alter_rumah_rumah_sewa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasos',
            fields=[
                ('id_fasos', models.AutoField(primary_key=True, serialize=False)),
                ('fasos', models.CharField(max_length=255)),
                ('lokasi_fasos', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nama_perumahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.perumahan')),
            ],
        ),
        migrations.CreateModel(
            name='RumahSusun',
            fields=[
                ('id_rumah_susun', models.AutoField(primary_key=True, serialize=False)),
                ('photo_rusun', models.ImageField(blank=True, null=True, upload_to='rusun_photo/')),
                ('alamat_rusun', models.CharField(max_length=255)),
                ('nama_rusun', models.CharField(max_length=255)),
                ('jumlah_kk', models.CharField(max_length=255)),
                ('jumlah_unit_kamar', models.CharField(max_length=255)),
                ('lokasi_rusun', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kelurahan')),
            ],
        ),
        migrations.CreateModel(
            name='SebaranRumahLiar',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('photo_ruli', models.ImageField(blank=True, null=True, upload_to='ruli_photo/')),
                ('alamat_ruli', models.CharField(max_length=255)),
                ('lokasi_ruli', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kelurahan')),
            ],
        ),
        migrations.CreateModel(
            name='Taman',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('photo_taman', models.ImageField(blank=True, null=True, upload_to='taman_photo/')),
                ('alamat_taman', models.CharField(max_length=255)),
                ('nama_taman', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_data.kelurahan')),
            ],
        ),
    ]
