# Generated by Django 5.1.2 on 2025-06-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0020_fasos_rumahsusun_sebaranrumahliar_taman'),
        ('maps', '0005_geodataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rumah_set', to='maps.geodataset'),
        ),
    ]
