# Generated by Django 5.1.2 on 2025-06-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0022_alter_rumah_geo'),
        ('maps', '0005_geodataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='geo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maps.geodataset'),
        ),
    ]
