# Generated by Django 5.1.2 on 2025-06-30 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0023_alter_rumah_geo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('disetujui', models.BooleanField(default=False)),
                ('ditolak', models.BooleanField(default=False)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('disetujui', models.BooleanField(default=False)),
                ('ditolak', models.BooleanField(default=False)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_rumah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.rumah')),
                ('nama_perumahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.perumahan')),
            ],
        ),
    ]
