# Generated by Django 5.1.2 on 2025-06-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0024_addrequest_updaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='photo_perumahan',
            field=models.ImageField(blank=True, null=True, upload_to='perumahan_photo/'),
        ),
        migrations.AddField(
            model_name='addrequest',
            name='photo_rumah',
            field=models.ImageField(blank=True, null=True, upload_to='rumah_photo/'),
        ),
    ]
