# Generated by Django 5.1.2 on 2025-07-01 00:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0025_addrequest_photo_perumahan_addrequest_photo_rumah'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='lokasi_rumah',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
