# Generated by Django 5.1.2 on 2025-07-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0026_addrequest_lokasi_rumah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequest',
            old_name='lokasi_rumah',
            new_name='geometry',
        ),
    ]
