# Generated by Django 5.1.2 on 2025-07-01 00:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0027_rename_lokasi_rumah_addrequest_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
