# Generated by Django 5.1.2 on 2025-07-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0028_alter_addrequest_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updaterequest',
            name='nama_perumahan',
        ),
    ]
