# Generated by Django 5.1.2 on 2025-07-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0030_updaterequest_photo_perumahan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumah',
            name='lokasi_rumah',
        ),
    ]
