# Generated by Django 5.1.2 on 2025-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0031_remove_rumah_lokasi_rumah'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='dibuat_oleh_users',
            field=models.UUIDField(blank=True, null=True, verbose_name='Dibuat oleh (Supabase User UUID)'),
        ),
    ]
