# Generated by Django 5.1.2 on 2025-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0032_updaterequest_dibuat_oleh_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='dibuat_oleh_users',
            field=models.CharField(blank=True, null=True),
        ),
    ]
