# Generated by Django 5.1.2 on 2025-07-03 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0033_alter_updaterequest_dibuat_oleh_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
