# Generated by Django 5.1.2 on 2025-07-03 18:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0034_updaterequest_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
