# Generated by Django 5.1.2 on 2025-07-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0035_alter_updaterequest_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sebaranrumahliar',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='sebaranrumahliar',
            name='kelurahan',
        ),
        migrations.RemoveField(
            model_name='taman',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='taman',
            name='kelurahan',
        ),
        migrations.DeleteModel(
            name='Fasos',
        ),
        migrations.DeleteModel(
            name='SebaranRumahLiar',
        ),
        migrations.DeleteModel(
            name='Taman',
        ),
    ]
