# Generated by Django 5.1.2 on 2025-07-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0036_remove_sebaranrumahliar_kecamatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumah',
            name='alamat_rumah',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='jumlah_kk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='nama_pemilik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='nama_perumahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_data.perumahan'),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='status_luas',
            field=models.CharField(blank=True, choices=[('LUAS_RUMAH_CUKUP', 'Luas Rumah Cukup'), ('LUAS_RUMAH_KURANG', 'Luas Rumah Kurang')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rumah',
            name='status_rumah',
            field=models.CharField(blank=True, choices=[('RUMAH_LAYAK_HUNI', 'Rumah Layak Huni'), ('RUMAH_TIDAK_LAYAK_HUNI', 'Rumah Tidak Layak Huni')], max_length=30, null=True),
        ),
    ]
