# Generated by Django 5.1.2 on 2025-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0037_alter_rumah_alamat_rumah_alter_rumah_jumlah_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='dibuat_oleh_users',
            field=models.CharField(blank=True, null=True),
        ),
    ]
