# Generated by Django 5.1.2 on 2025-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0038_addrequest_dibuat_oleh_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumah',
            name='dibuat_oleh_users',
            field=models.CharField(blank=True, null=True),
        ),
    ]
